In [1]:
import numpy as np
import random
from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import math
import scipy.stats as st
from mpl_toolkits.mplot3d import Axes3D 
import matplotlib.pyplot as plt 
import numpy as np 
import copy
n=3
nn=3
divide_number=100;
object_number=1.0
batch_size=128
width=0.000001
width1=0.000001

In [2]:
def distribution1(i):
    x=0;
    #x=np.random.uniform(0, 1, size=1);
    R=np.random.randint(2);
    if (R==0):
        x=np.random.normal(0.1, 0.1, size=1);
    elif(R==1):
        x=np.random.normal(0.9, 0.1, size=1);
    if(x<=0):
        x=0;
    return x;

def distribution():
    list_temp=np.random.rand(nn);
    for ii in range(len(list_temp)):
        list_temp[ii]=distribution1(ii)
    list_temp=np.array(list_temp)
    #list_temp=sorted(list_temp,reverse=1);
    return list_temp;
print(distribution())

[0.         0.13456156 0.03275772]


In [3]:
possible = np.zeros((n,divide_number+1), dtype=np.double)
for j in range(0,n):
    for i in range(100000):#100000
        x=distribution1(j%5)*divide_number
        temp=int(x)
        #print(o,temp)
        if(temp>divide_number):
            temp=divide_number
        possible[j][temp]+=1/100000;
        
P = np.zeros((n,divide_number+1), dtype=np.double)
for j in range(0,n):
    P[j][0]=possible[j][0]
    for i in range(1,divide_number+1):
        P[j][i]=P[j][i-1]+possible[j][i];
print(P)

[[0.0921  0.10681 0.12274 0.13915 0.1567  0.17471 0.19367 0.2135  0.23332
  0.25365 0.27428 0.29425 0.31394 0.33257 0.35019 0.36654 0.38317 0.3981
  0.41167 0.42462 0.43574 0.4457  0.45453 0.46252 0.46928 0.47543 0.4806
  0.48481 0.48884 0.49176 0.49427 0.49614 0.49779 0.49906 0.50001 0.50073
  0.50134 0.50171 0.50194 0.50219 0.50248 0.50261 0.50268 0.50277 0.50281
  0.50282 0.50287 0.50287 0.50287 0.50291 0.50293 0.50295 0.50297 0.503
  0.50303 0.50311 0.50323 0.50338 0.50354 0.50363 0.50386 0.50424 0.50465
  0.50515 0.50601 0.5069  0.50836 0.50995 0.51168 0.51416 0.51716 0.52042
  0.52467 0.53002 0.53622 0.54352 0.55134 0.56069 0.57116 0.58253 0.59461
  0.60833 0.62288 0.63953 0.65606 0.67422 0.69263 0.71145 0.73086 0.75042
  0.76985 0.7893  0.80829 0.82656 0.84441 0.86167 0.87858 0.89334 0.90715
  0.91962 1.     ]
 [0.09207 0.10556 0.1208  0.13736 0.15461 0.17221 0.19107 0.21107 0.23037
  0.25003 0.27058 0.28951 0.30823 0.32715 0.34542 0.36254 0.37834 0.39298
  0.40728 0.42045 0.431

In [4]:
dp = np.zeros(((nn+2),  divide_number+1,(nn+2)), dtype=np.double)
record_dp = np.zeros(((nn+2), divide_number+1,(nn+2)), dtype=np.double)
for yes in range(0,nn+1):
    for money in range(0,divide_number+1):
        if money == 0:
            dp[0, 0, yes] = 0
        else:
            dp[0, money, yes] = yes# + 1.0
        
        
for i in range(1,nn+1):
    for yes in range(0,nn+1):
        for money in range(divide_number+1):
            min_num=99999;
            for o in range(0,money+1):
                if( min_num>(1.0-P[nn-i,o])*dp[i-1,money-o,min(yes + 1, n)]+P[nn-i,o]*(dp[i-1,money,yes]+1)):
                    record_dp[i,money,yes]=o;
                    min_num=(1.0-P[nn-i,o])*dp[i-1,money-o,min(yes + 1, n)]+P[nn-i,o]*(dp[i-1,money,yes]+1)
                    
            dp[i,money,yes]=min_num;

In [5]:
print(dp[n,divide_number,0]);
print(record_dp[n,divide_number,0]);
print(temp)


1.7789255553480032
48.0
74


In [6]:
def plan_dp(temp):
    #print(temp)
    remain=divide_number
    yes=0;
    ans =0;
    o_list=[];
    remain_list=[];
    for i in range(nn,0,-1):
        o=record_dp[i,remain,yes]
        #print(o,remain)
        o_list.append(o)
        remain_list.append(remain);
        if(o<temp[nn-i]):
            remain-=int(o);
            
            yes+=1;
        elif (remain>0):
            ans+=1;
    if(remain<=0):
        return ans,o_list;
    else:
        return nn,o_list;
    

In [7]:
ans_list=[];
for i in range(1000):
    temp=distribution()*divide_number   
    ans_list.append(plan_dp(temp)[0]);
    print("\n",temp)
    print(plan_dp(temp))



 [88.41348001 27.47317973 80.46764099]
(1, [48.0, 52.0, 52.0])

 [ 86.62353852  81.03414546 100.46379416]
(0, [48.0, 52.0, 0.0])

 [26.06206815 28.46432908 98.22471768]
(3, [48.0, 50.0, 100.0])

 [27.76196244  4.29412951 17.709232  ]
(3, [48.0, 50.0, 100.0])

 [16.35034322  3.17714048 88.89804836]
(3, [48.0, 50.0, 100.0])

 [95.24626999 84.75974323  8.56959528]
(0, [48.0, 52.0, 0.0])

 [98.52903329 23.81435162 13.94613325]
(3, [48.0, 52.0, 52.0])

 [42.59505609 97.61903289  5.77242579]
(3, [48.0, 50.0, 50.0])

 [10.98940607 14.07741977 75.01606603]
(3, [48.0, 50.0, 100.0])

 [ 88.28143883  94.6039238  103.2816371 ]
(0, [48.0, 52.0, 0.0])

 [15.28112914  9.493189   10.73649494]
(3, [48.0, 50.0, 100.0])

 [84.9784726  25.60633718  6.99876047]
(3, [48.0, 52.0, 52.0])

 [ 0.         12.85213061 11.47139418]
(3, [48.0, 50.0, 100.0])

 [ 87.3516099   11.98789566 105.0790202 ]
(1, [48.0, 52.0, 52.0])

 [91.20221119 95.18304623 18.49158316]
(0, [48.0, 52.0, 0.0])

 [ 23.79155596  96.28067078 

 [93.94319752 92.04547322 12.49615316]
(0, [48.0, 52.0, 0.0])

 [93.17312748 85.18902319  0.        ]
(0, [48.0, 52.0, 0.0])

 [ 77.87062554 101.15263444  79.84647485]
(0, [48.0, 52.0, 0.0])

 [72.96520893  8.41897915  9.1647727 ]
(3, [48.0, 52.0, 52.0])

 [92.02605793  5.45273555  4.971557  ]
(3, [48.0, 52.0, 52.0])

 [17.10792392 82.69211706 77.87068158]
(1, [48.0, 50.0, 50.0])

 [103.40092873  80.84717565  80.52885641]
(0, [48.0, 52.0, 0.0])

 [64.93685573 89.73407713  5.87167797]
(0, [48.0, 52.0, 0.0])

 [ 0.         14.69223919 97.08933624]
(3, [48.0, 50.0, 100.0])

 [  1.80672188 107.46685832   8.17160268]
(3, [48.0, 50.0, 50.0])

 [10.49841103  0.         83.37472838]
(3, [48.0, 50.0, 100.0])

 [15.60336838 97.04846907 92.28335104]
(1, [48.0, 50.0, 50.0])

 [13.74434738 33.16340113 86.79999976]
(3, [48.0, 50.0, 100.0])

 [92.47294123 91.8717253   0.        ]
(0, [48.0, 52.0, 0.0])

 [98.0165379  80.81030228 78.24372525]
(0, [48.0, 52.0, 0.0])

 [91.79325227 12.22592035  4.645066


 [86.13561026 89.04977824  1.11563941]
(0, [48.0, 52.0, 0.0])

 [11.3518225  30.33871791 80.39441985]
(3, [48.0, 50.0, 100.0])

 [12.42890907  0.         23.05068945]
(3, [48.0, 50.0, 100.0])

 [82.41886525  0.         12.64611103]
(3, [48.0, 52.0, 52.0])

 [86.45638759  9.2761069  84.3466787 ]
(1, [48.0, 52.0, 52.0])

 [ 71.49804952  92.52989695 100.23598385]
(0, [48.0, 52.0, 0.0])

 [74.0796702  13.49305442  3.34579276]
(3, [48.0, 52.0, 52.0])

 [84.56034464 82.13134284 91.83390102]
(0, [48.0, 52.0, 0.0])

 [12.49163545 18.70587599 17.01336728]
(3, [48.0, 50.0, 100.0])

 [ 78.47223096   9.50562473 104.94227008]
(1, [48.0, 52.0, 52.0])

 [ 4.01079303 18.45125376 77.39456591]
(3, [48.0, 50.0, 100.0])

 [ 5.13669784 83.84736899  2.9568035 ]
(3, [48.0, 50.0, 50.0])

 [ 0.         88.65419351  1.93994024]
(3, [48.0, 50.0, 50.0])

 [89.36877971 18.21703465 28.90168983]
(3, [48.0, 52.0, 52.0])

 [91.31983599  0.         93.55421257]
(1, [48.0, 52.0, 52.0])

 [101.43452349  87.17284145  83.

 [ 14.32299248  79.8422001  100.75137314]
(1, [48.0, 50.0, 50.0])

 [74.27707543 96.50830096 11.85935318]
(0, [48.0, 52.0, 0.0])

 [ 21.5960552   17.62637347 105.52122155]
(2, [48.0, 50.0, 100.0])

 [ 0.         91.93990492  5.3955248 ]
(3, [48.0, 50.0, 50.0])

 [77.89581528  0.          0.        ]
(3, [48.0, 52.0, 52.0])

 [25.48350588  0.09813698 11.83832646]
(3, [48.0, 50.0, 100.0])

 [10.4174269  76.87489549  0.        ]
(3, [48.0, 50.0, 50.0])

 [  5.75924505 104.74253269 101.71892106]
(1, [48.0, 50.0, 50.0])

 [ 7.55439463  7.38345494 11.32757941]
(3, [48.0, 50.0, 100.0])

 [102.44435185  17.31853356  89.68388464]
(1, [48.0, 52.0, 52.0])

 [92.12999025 80.63855939  0.        ]
(0, [48.0, 52.0, 0.0])

 [ 25.1317613    0.         100.36608463]
(2, [48.0, 50.0, 100.0])

 [95.88663664 83.73419847 76.41010104]
(0, [48.0, 52.0, 0.0])

 [14.50420428 77.06257667 89.64741374]
(1, [48.0, 50.0, 50.0])

 [84.74988415 88.23084722  6.19213478]
(0, [48.0, 52.0, 0.0])

 [ 7.99634819 91.06768064

In [8]:
print(sum(ans_list)/len(ans_list))

1.704
