In [1]:
import itertools
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torch.distributions as D
from torch.utils.data import DataLoader, TensorDataset

n = 5
epochs = 10
supervisionEpochs = 0
lr = 0.001
log_interval = 20
trainSize = 100000
penaltyLambda = 10
doublePeakHighMean = 0.9
doublePeakLowMean = 0.1
doublePeakStd = 0.1

d1 = D.normal.Normal(doublePeakLowMean, doublePeakStd)
d2 = D.normal.Normal(doublePeakHighMean, doublePeakStd)
distributionRatio = (d1.cdf(1) + d2.cdf(1) - d1.cdf(0) - d2.cdf(0)) / 2
distributionBase = d1.cdf(0) + d2.cdf(0)


def cdf(x, i=None):
    return (d1.cdf(x) + d2.cdf(x) - distributionBase) / 2 / distributionRatio

# def cdf(x, i=None):
#     if x < 0.1:
#         return 0
#     if x <= 0.2:
#         return 0.5 * (x - 0.1) / 0.1
#     if x < 0.8:
#         return 0.5
#     if x < 0.9:
#         return 0.5 + 0.5 * (x - 0.8) / 0.1
#     return 1


print(distributionBase)

tensor(0.1587)


In [2]:
signals = np.random.randint(2, size=(trainSize, n))
# samples1 = np.random.uniform(low=0.1, high=0.2, size=(trainSize, n))
# samples2 = np.random.uniform(low=0.8, high=0.9, size=(trainSize, n))
samples1 = np.random.normal(
    loc=doublePeakLowMean, scale=doublePeakStd, size=(trainSize, n)
)
for i in range(trainSize):
    for j in range(n):
        while samples1[i, j] < 0 or samples1[i, j] > 1:
            samples1[i, j] = np.random.normal(
                loc=doublePeakLowMean, scale=doublePeakStd
            )
samples2 = np.random.normal(
    loc=doublePeakHighMean, scale=doublePeakStd, size=(trainSize, n)
)
for i in range(trainSize):
    for j in range(n):
        while samples2[i, j] < 0 or samples2[i, j] > 1:
            samples2[i, j] = np.random.normal(
                loc=doublePeakHighMean, scale=doublePeakStd
            )
samplesJoint = signals * samples1 - (signals - 1) * samples2
tp_tensor = torch.tensor(samplesJoint, dtype=torch.float32)
# tp_tensor = torch.tensor(np.random.rand(10000, n), dtype=torch.float32)
tp_dataset = TensorDataset(tp_tensor[: round(trainSize * 0.3)])
tp_dataset_testing = TensorDataset(tp_tensor[round(trainSize * 0.7) :])
tp_dataloader = DataLoader(tp_dataset, batch_size=128, shuffle=True)
tp_dataloader_testing = DataLoader(tp_dataset_testing, batch_size=256, shuffle=False)


# for mapping binary to payments before softmax
model = nn.Sequential(
    nn.Linear(n, 100),
    nn.ReLU(),
    nn.Linear(100, 100),
    nn.ReLU(),
    nn.Linear(100, 100),
    nn.ReLU(),
    nn.Linear(100, n),
)


# optimizer = optim.SGD(model.parameters(), lr=lr)
optimizer = optim.Adam(model.parameters(), lr=lr)


In [3]:
def bitsToPayments(bits):
    if sum(bits).item() == 0:
        return torch.ones(n)
    bits = bits.type(torch.float32)
    negBits = torch.ones(n) - bits
    payments = model(bits)
    payments = payments - 1000 * negBits
    payments = torch.softmax(payments, 0)
    payments = payments + negBits
    return payments


def tpToBits(tp, bits=torch.ones(n).type(torch.uint8)):
    payments = bitsToPayments(bits)
    newBits = (tp >= payments).type(torch.uint8)
    
    if torch.equal(newBits, bits):
        return bits
    else:
        return tpToBits(tp, newBits)#bits-bits#tpToBits(tp, newBits)


def tpToPayments(tp):
    return bitsToPayments(tpToBits(tp))


def tpToTotalDelay(tp):
    return n - sum(tpToBits(tp).type(torch.float32))


In [4]:
print(1_000_000)
print(cdf(0.5))

1000000
tensor(0.5000)


In [5]:
dpPrecision = 100
# howManyPpl left, money left, yes already
dp = np.zeros([n + 1, dpPrecision + 1, n + 1])
decision = np.zeros([n + 1, dpPrecision + 1, n + 1], dtype=np.uint8)
# ppl = 0 left
for yes in range(n + 1):
    for money in range(dpPrecision + 1):
        if money == 0:
            dp[0, 0, yes] = 0
        else:
            dp[0, money, yes] = yes# + 1.0
for ppl in range(1, n + 1):
    for yes in range(n + 1):
        for money in range(dpPrecision + 1):
            minSoFar = 1_000_000
            for offerIndex in range(money + 1):
                offer = offerIndex / dpPrecision
                res = (1 - cdf(offer)) * dp[
                    ppl - 1, money - offerIndex, min(yes + 1, n)
                ] + cdf(offer) * (1 + dp[ppl - 1, money, yes])
                if minSoFar > res:
                    minSoFar = res
                    decision[ppl, money, yes] = offerIndex
            dp[ppl, money, yes] = minSoFar


In [6]:
print(dp[n, dpPrecision, 0])

1.8651759624481201


In [7]:
# howManyPpl left, money left, yes already
dp_H = np.zeros([n + 1, dpPrecision + 1])
decision_H = np.zeros([n + 1, dpPrecision + 1], dtype=np.uint8)
# ppl = 0 left
for money in range(dpPrecision + 1):
    if money == 0:
        dp_H[0, 0] = 1
    else:
        offer = money / dpPrecision
        dp_H[0, money] = 0#cdf(offer)# + 1.0
for ppl in range(1, n + 1):
    for money in range(dpPrecision + 1):
        maxSoFar = -1_000_000
        for offerIndex in range(money + 1):
            offer = offerIndex / dpPrecision
            res = (1-cdf(offer)) * dp_H[
                 ppl - 1, money - offerIndex
                ]
            if maxSoFar < res:
                maxSoFar = res
                decision_H[ppl, money] = offerIndex
        dp_H[ppl, money] = maxSoFar
print(dp_H[n, dpPrecision])
print(5*(1-dp_H[n, dpPrecision]))

0.28367453813552856
3.581627309322357


In [8]:
print(samplesJoint)

[[0.18034192 0.92015969 0.0806884  0.17887893 0.02430093]
 [0.96237549 0.09351275 0.95911953 0.22012127 0.96389697]
 [0.98718016 0.02469703 0.78104115 0.96758379 0.05342462]
 ...
 [0.15225455 0.13962683 0.13745683 0.23356596 0.05642131]
 [0.85601341 0.84067523 0.10099183 0.93241787 0.51645455]
 [0.75414403 0.85553079 0.01291764 0.1626883  0.09552752]]


In [9]:
def plan_dp(temp):
    #print(temp)
    remain=dpPrecision
    yes=0;
    ans =0;
    o_list=[];
    remain_list=[];
    for ppl in range(n,0,-1):
        o=decision[ppl, remain, yes]
        #print(o,remain)
        o_list.append(o)
        remain_list.append(remain);
        if(o<temp[n-ppl]):
            remain-=int(o);
            yes+=1;
        elif (remain>0):
            ans+=1;
    if(remain<=0):
        return ans,o_list;
    else:
        return n,o_list;
    

In [10]:
ans_list=[];
for i in range(10000):
    temp=samplesJoint[i]*dpPrecision
    #print(temp)
    ans_list.append(plan_dp(temp)[0]);
    #print("\n",temp)
    #print(plan_dp(temp))
print(sum(ans_list)/len(ans_list))

1.9034


In [11]:
def dpSupervisionRule(tp):
    tp = list(tp.numpy())
    bits = [1 for ii in range(n)]
    payments = [0 for ii in range(n)]
    money = dpPrecision
    yes = 0
    for i in range(n):
        offerIndex = decision[n - i, money, yes]
        offer = offerIndex / dpPrecision
        if tp[i] >= offer:
            money -= offerIndex
            yes += 1
            bits[i] = 1
            payments[i] = offer
        else:
            bits[i] = 0
            payments[i] = 1
    if money > 0:
        bits = [0 for ii in range(n)]
        payments = [1 for ii in range(n)]
    bits = torch.tensor(bits, dtype=torch.uint8)
    payments = torch.tensor(payments, dtype=torch.float32)
    # print()
    # print(tp)
    # print(bits)
    # print(payments)
    # print()
    return (bits, payments)


def heuristicSupervisionRule(tp):
    tp = list(tp.numpy())
    bits = [1 for ii in range(n)]
    payments = [0 for ii in range(n)]
    money = dpPrecision
    yes = 0
    for i in range(n):
        offerIndex = decision_H[n - i, money]
        offer = offerIndex / dpPrecision
        if tp[i] >= offer:
            money -= offerIndex
            yes += 1
            bits[i] = 1
            payments[i] = offer
        else:
            bits = [0 for ii in range(n)]
            payments = [1 for ii in range(n)]
            money=1
            #bits[i] = 0
            #payments[i] = 0#1
            break
    if money > 0:
        bits = [0 for ii in range(n)]
        payments = [1 for ii in range(n)]

    bits = torch.tensor(bits, dtype=torch.float32)
    payments = torch.tensor(payments, dtype=torch.float32)
    # print()
    # print(tp)
    # print(bits)
    # print(payments)
    # print()
    return (bits, payments)

def dpDelay(tp):
    bits, payments = dpSupervisionRule(tp)
    totalPayment = torch.dot(bits.type(torch.float32), payments).item()
    if totalPayment < 1:
        return n
    else:
        return n - sum(bits).item()


def costSharingSupervisionRule(tp):
    tp = list(tp.numpy())
    for k in range(n, -1, -1):
        if k == 0:
            break
        bits = [1 if tp[ii] >= 1 / k else 0 for ii in range(n)]
        if sum(bits) == k:
            break
    if k == 0:
        payments = [1 for ii in range(n)]
    else:
        payments = [1 / k if bits[ii] == 1 else 1 for ii in range(n)]
    bits = torch.tensor(bits, dtype=torch.uint8)
    payments = torch.tensor(payments, dtype=torch.float32)
    return (bits, payments)


def costSharingDelay(tp):
    return n - sum(costSharingSupervisionRule(tp)[0]).item()

def heuristicDelay(tp):
    if(sum(heuristicSupervisionRule(tp)[0]).item()==n):
        return 0;
    else:
        return n;

In [12]:
for i in range(n, 0, -1):
            print([1 if ii >= i else 0 for ii in range(n)])
            print(
                    tpToPayments(
                            torch.tensor([0 if ii >= i else 1 for ii in range(n)], dtype=torch.float32)
                    )
                )

[0, 0, 0, 0, 0]
tensor([0.2309, 0.2092, 0.2066, 0.1558, 0.1975], grad_fn=<AddBackward0>)
[0, 0, 0, 0, 1]
tensor([0.2850, 0.2678, 0.2543, 0.1929, 1.0000], grad_fn=<AddBackward0>)
[0, 0, 0, 1, 1]
tensor([0.3512, 0.3319, 0.3169, 1.0000, 1.0000], grad_fn=<AddBackward0>)
[0, 0, 1, 1, 1]
tensor([0.5161, 0.4839, 1.0000, 1.0000, 1.0000], grad_fn=<AddBackward0>)
[0, 1, 1, 1, 1]
tensor([1., 1., 1., 1., 1.], grad_fn=<AddBackward0>)


In [13]:
allBits = [torch.tensor(bits) for bits in itertools.product([0, 1], repeat=n)]
print(allBits)

for batch_idx, (tp_batch,) in enumerate(tp_dataloader_testing):
    penalty = 0
    for bitsMoreOnes in allBits:
        for i in range(n):
            if bitsMoreOnes[i] == 1:
                bitsLessOnes = bitsMoreOnes.clone()
                bitsLessOnes[i] = 0
                penalty = penalty + sum(
                        torch.relu(
                            bitsToPayments(bitsMoreOnes) - bitsToPayments(bitsLessOnes)
                        )
                    )
    loss = penalty * penaltyLambda
    for tp in tp_batch:
            for i in range(n):
                tp1 = tp.clone()
                tp1[i] = 1
                tp0 = tp.clone()
                tp0[i] = 0
                offer = tpToPayments(tp1)[i]
                delay1 = tpToTotalDelay(tp1)
                delay0 = tpToTotalDelay(tp0)
                #loss = loss + (1 - cdf(offer)) * delay1 + cdf(offer) * delay0
                loss = loss + (1 - cdf(offer)) * delay1 + cdf(offer) * delay0
    print()
    print(tp)
    tp1 = tp.clone()
    tp1[0] = 1
    tp0 = tp.clone()
    tp0[0] = 0
    offer = tpToPayments(tp1)[0]
    print(offer)
    print(tpToPayments(tp1))
    print(delay1)
    print(delay0)
    break;
#print(loss)
#print(penalty)

[tensor([0, 0, 0, 0, 0]), tensor([0, 0, 0, 0, 1]), tensor([0, 0, 0, 1, 0]), tensor([0, 0, 0, 1, 1]), tensor([0, 0, 1, 0, 0]), tensor([0, 0, 1, 0, 1]), tensor([0, 0, 1, 1, 0]), tensor([0, 0, 1, 1, 1]), tensor([0, 1, 0, 0, 0]), tensor([0, 1, 0, 0, 1]), tensor([0, 1, 0, 1, 0]), tensor([0, 1, 0, 1, 1]), tensor([0, 1, 1, 0, 0]), tensor([0, 1, 1, 0, 1]), tensor([0, 1, 1, 1, 0]), tensor([0, 1, 1, 1, 1]), tensor([1, 0, 0, 0, 0]), tensor([1, 0, 0, 0, 1]), tensor([1, 0, 0, 1, 0]), tensor([1, 0, 0, 1, 1]), tensor([1, 0, 1, 0, 0]), tensor([1, 0, 1, 0, 1]), tensor([1, 0, 1, 1, 0]), tensor([1, 0, 1, 1, 1]), tensor([1, 1, 0, 0, 0]), tensor([1, 1, 0, 0, 1]), tensor([1, 1, 0, 1, 0]), tensor([1, 1, 0, 1, 1]), tensor([1, 1, 1, 0, 0]), tensor([1, 1, 1, 0, 1]), tensor([1, 1, 1, 1, 0]), tensor([1, 1, 1, 1, 1])]

tensor([0.9211, 0.2104, 0.0344, 0.8680, 0.2301])
tensor(0.5738, grad_fn=<SelectBackward>)
tensor([0.5738, 1.0000, 1.0000, 0.4262, 1.0000], grad_fn=<AddBackward0>)
tensor(2.)
tensor(3.)


In [14]:
allBits = [torch.tensor(bits) for bits in itertools.product([0, 1], repeat=n)]

runningLossNN = []
runningLossCS = []
runningLossDP = []
runningLossHeuristic = []

def recordAndReport(name, source, loss, n=100):
    source.append(loss)
    realLength = min(n, len(source))
    avgLoss = sum(source[-n:]) / realLength
    print(f"{name} ({realLength}): {avgLoss}")


def supervisionTrain(epoch, supervisionRule):
    model.train()
    for batch_idx, (tp_batch,) in enumerate(tp_dataloader):
        optimizer.zero_grad()
        loss = 0
        for tp in tp_batch:
            bits, payments = supervisionRule(tp)
            # print()
            # print("supervision")
            # print(tp)
            # print(bits)
            # print()
            # print(payments)
            # print(bitsToPayments(bits))
            # print()
            loss = loss + F.mse_loss(bitsToPayments(bits), payments)

        loss = loss / len(tp_batch)
        loss.backward()
        optimizer.step()
        if batch_idx % log_interval == 0:
            print(
                "Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}".format(
                    epoch,
                    batch_idx * len(tp_batch),
                    len(tp_dataloader.dataset),
                    100.0 * batch_idx / len(tp_dataloader),
                    loss.item(),
                )
            )


def train(epoch):
    model.train()
    for batch_idx, (tp_batch,) in enumerate(tp_dataloader):
        optimizer.zero_grad()
        penalty = 0
        for bitsMoreOnes in allBits:
            for i in range(n):
                if bitsMoreOnes[i] == 1:
                    bitsLessOnes = bitsMoreOnes.clone()
                    bitsLessOnes[i] = 0
                    penalty = penalty + sum(
                        torch.relu(
                            bitsToPayments(bitsMoreOnes) - bitsToPayments(bitsLessOnes)
                        )
                    )
        loss = penalty * penaltyLambda
        # costSharingLoss = 0
        # dpLoss = 0
        for tp in tp_batch:
            # costSharingLoss += costSharingDelay(tp)
            # dpLoss += dpDelay(tp)
            # print()
            # print("---")
            # print(tp)
            # print(costSharingSupervisionRule(tp))
            # print(dpSupervisionRule(tp))
            # print(costSharingDelay(tp), dpDelay(tp))
            # print()
            for i in range(n):
                tp1 = tp.clone()
                tp1[i] = 1
                tp0 = tp.clone()
                tp0[i] = 0
                offer = tpToPayments(tp1)[i]
                delay1 = tpToTotalDelay(tp1)
                delay0 = tpToTotalDelay(tp0)
                loss = loss + (1 - cdf(offer)) * delay1 + cdf(offer) * delay0

        loss = loss / len(tp_batch) / n
        # costSharingLoss /= len(tp_batch)
        # dpLoss /= len(tp_batch)
        loss.backward()
        optimizer.step()
        if batch_idx % log_interval == 0:
            print(
                "Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}".format(
                    epoch,
                    batch_idx * len(tp_batch),
                    len(tp_dataloader.dataset),
                    100.0 * batch_idx / len(tp_dataloader),
                    loss.item(),
                )
            )
            # recordAndReport("NN", runningLossNN, loss.item())
            # recordAndReport("CS", runningLossCS, costSharingLoss)
            # recordAndReport("DP", runningLossDP, dpLoss)
            # print(dp[n, dpPrecision, 0])
            print("penalty:",penalty.item())
            # print(distributionRatio)
            # for i in range(n, 0, -1):
            #     print(
            #         tpToPayments(
            #             torch.tensor([1] * i + [0] * (n - i), dtype=torch.float32)
            #         )
            #     )


In [15]:
def test():
    model.eval()
    with torch.no_grad():
        costSharingLoss = 0
        dpLoss = 0
        nnLoss = 0
        heuristicLoss=0
        lenLoss= 0
        for (tp_batch,) in tp_dataloader_testing:

            for tp in tp_batch:
                costSharingLoss += costSharingDelay(tp)
                dpLoss += dpDelay(tp)
                nnLoss += tpToTotalDelay(tp)
                heuristicLoss+= heuristicDelay(tp)
            lenLoss+=len(tp_batch)
        costSharingLoss /= lenLoss
        dpLoss /= lenLoss
        nnLoss /= lenLoss
        heuristicLoss /= lenLoss
        print(lenLoss)
        recordAndReport("NN", runningLossNN, nnLoss)
        recordAndReport("CS", runningLossCS, costSharingLoss)
        recordAndReport("DP", runningLossDP, dpLoss)
        recordAndReport("heuristic", runningLossHeuristic, heuristicLoss)
        print(dp[n, dpPrecision,0])
        for i in range(n, 0, -1):
            print(
                    tpToPayments(
                            torch.tensor([0 if ii >= i else 1 for ii in range(n)], dtype=torch.float32)
                    )
                )

#model=torch.load("save/pytorchNN=5dp1");
#model.eval()
for epoch in range(1, supervisionEpochs + 1):
    print(distributionRatio)
#    #supervisionTrain(epoch, costSharingSupervisionRule)
#    supervisionTrain(epoch, dpSupervisionRule)
    supervisionTrain(epoch, heuristicSupervisionRule)
test()

for epoch in range(1, epochs + 1):
    train(epoch)
    test()


30000
NN (1): 2.524766683578491
CS (1): 2.5370333333333335
DP (1): 1.8649
heuristic (1): 3.585166666666667
1.8651759624481201
tensor([0.2309, 0.2092, 0.2066, 0.1558, 0.1975])
tensor([0.2850, 0.2678, 0.2543, 0.1929, 1.0000])
tensor([0.3512, 0.3319, 0.3169, 1.0000, 1.0000])
tensor([0.5161, 0.4839, 1.0000, 1.0000, 1.0000])
tensor([1., 1., 1., 1., 1.])
Train Epoch: 1 [0/30000 (0%)]	Loss: 2.711947
penalty: 0.0
Train Epoch: 1 [2560/30000 (9%)]	Loss: 2.075199
penalty: 0.06699621677398682
Train Epoch: 1 [5120/30000 (17%)]	Loss: 1.964900
penalty: 0.01714484393596649
Train Epoch: 1 [7680/30000 (26%)]	Loss: 2.103004
penalty: 0.026439543813467026
Train Epoch: 1 [10240/30000 (34%)]	Loss: 1.800888
penalty: 0.0011539459228515625
Train Epoch: 1 [12800/30000 (43%)]	Loss: 1.776842
penalty: 0.021195389330387115
Train Epoch: 1 [15360/30000 (51%)]	Loss: 1.964517
penalty: 0.015377651900053024
Train Epoch: 1 [17920/30000 (60%)]	Loss: 1.737738
penalty: 0.013531327247619629
Train Epoch: 1 [20480/30000 (68%)]	L

Train Epoch: 7 [17920/30000 (60%)]	Loss: 1.614754
penalty: 0.008042693138122559
Train Epoch: 7 [20480/30000 (68%)]	Loss: 1.836746
penalty: 0.0019801855087280273
Train Epoch: 7 [23040/30000 (77%)]	Loss: 1.817667
penalty: 0.0009642839431762695
Train Epoch: 7 [25600/30000 (85%)]	Loss: 1.762058
penalty: 0.003320753574371338
Train Epoch: 7 [28160/30000 (94%)]	Loss: 1.691307
penalty: 0.0017093420028686523
30000
NN (8): 1.857337474822998
CS (8): 2.5370333333333335
DP (8): 1.8649000000000002
heuristic (8): 3.5851666666666664
1.8651759624481201
tensor([0.7444, 0.0624, 0.0627, 0.0657, 0.0647])
tensor([0.7540, 0.0822, 0.0797, 0.0842, 1.0000])
tensor([0.7726, 0.1079, 0.1195, 1.0000, 1.0000])
tensor([0.7870, 0.2130, 1.0000, 1.0000, 1.0000])
tensor([1., 1., 1., 1., 1.])
Train Epoch: 8 [0/30000 (0%)]	Loss: 1.768989
penalty: 0.0
Train Epoch: 8 [2560/30000 (9%)]	Loss: 1.714049
penalty: 0.0
Train Epoch: 8 [5120/30000 (17%)]	Loss: 1.666453
penalty: 0.0
Train Epoch: 8 [7680/30000 (26%)]	Loss: 1.903282
pen

In [16]:

torch.save(model, "save/pytorchNN=5UN1")

In [17]:
#model = torch.load(PATH)
#model.eval()